version: "2"
services:
  api:
    build: ./docker/api
    container_name: api
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./docker/api/app:/usr/src/app
      # Mount the node_modules vulume, otherwise it will be gone after mounting
      - /usr/src/app/node_modules